### ISSUE TITLE
A way to add users to map ?

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-website#21]
Is there a way to add some users to the map http://geotrek.fr/utilisateurs.html ?

A GeoJSON to complet on http://utilisateurs.geotrek.fr/ ?

As there are some more to include. 
2017 users : http://geotrek.ecrins-parcnational.fr/rencontres/2017/2017-10-carte-utilisateurs-geotrek.jpg

I would just add those who are really using it, not those who are studying it.

**Comment by gutard** [comment]
You can't (for now). http://utilisateurs.geotrek.fr/ is an internal tool at Makina Corpus. But you can send the names to us by email as I already said to you.

**Comment by camillemonchicourt** [comment]
OK good, I'll do that.
