### ISSUE TITLE
Nouvelle page documentation

### ISSUE THREAD

**Issue by numahell** [makinacorpus/Geotrek-website#52]
La page ressources n'est pas très pratique, et nous avons besoin de regrouper les liens vers les documentations des produits Geotrek sur une même page.

Voici une ébauche de proposition de page pour la documentation

![Board](https://github.com/GeotrekCE/Geotrek-website/assets/546686/3309d33d-730e-4c34-95c9-8cec7fccba42)

L'idée est de mettre un lien "Documentation" à la place de "Ressources" 

La section "autres ressources" regrouperait les liens non listés plus haut.

On peut ajouter un lien dans le footer dans la section communauté "Rencontres Geotrek", où on regrouperait tous les liens vers les rencontres depuis le début.

**Comment by camillemonchicourt** [comment]
OK, merci pour ces éléments.
En effet la page "Ressources" mérite d'être revue pour être plus lisible et plus efficace.

Le dilemme que j'avais eu quand j'avais fait cette première version de la page était entre : 
- Renvoyer vers des pages globales et génériques regroupant plusieurs ressources
- Renvoyer vers des ressources précises bien identifiées

La première solution est pérenne mais ne met pas en avant des ressources précises sur un sujet (Apidae, tel article sur tel sujet...)
La seconde est incomplète, partielle et très vite plus à jour.

Il y a notamment beaucoup de choses dans l'espace de ressources partagées sur https://geotrek.ecrins-parcnational.fr/ressources/.

Pour illustrer, on peut décider de renvoyer vers une ressources "Outils partagés" pointant sur https://geotrek.ecrins-parcnational.fr/ressources/outils/, ou vers "Guide de saisie du département du Gard" pointant sur https://geotrek.ecrins-parcnational.fr/ressources/outils/2020-07-Protocole-saisie-parcours-Rando-Gard.pdf.
La deuxième solution est plus claire et efficace, mais il me semble qu'il y a trop de choses pour que ce soit lisible et impossible à tenir à jour.

Idem pour les ressources techniques (https://geotrek.ecrins-parcnational.fr/ressources/technique/), les rapports de stage (https://geotrek.ecrins-parcnational.fr/ressources/stages/), les compte-rendus du COPIL et des groupes de travail, les supports de présentation partagés (https://geotrek.ecrins-parcnational.fr/ressources/presentations/), les cahiers des charges partagés (https://geotrek.ecrins-parcnational.fr/ressources/cctp/).

Idem pour les ressources externes comme : 
- https://pro.auvergnerhonealpes-tourisme.com/passerelle-apidae-geotrek-pour-diffuser-des-itineraires/
- https://pro.cirkwi.com/importez-vos-donnees-geotrek-dans-cirkwi/

Concernant les documents des rencontres, ce sont notamment les supports de présentation et les vidéos qui intéressent souvent des structures nouvelles ou des personnes n'ayant pas pu être présentes.
Pour moi, elles n'ont pas vraiment de raison d'être plus dans une page à part que les "guides", "tutoriels", "liens rapides".

**Comment by babastienne** [comment]
Je pense que c'est important déjà de nous accorder sur le constat actuel : la page des ressources n'est pas à jour.

- Certains liens mènent vers des erreurs 404
- Certaines ressources ne sont plus adaptées (Tutoriel installation Geotrek Jamaica, Vidéo présentation de Rando Ecrin, guide d'installation de Geotrek-Rando qui redirige vers l'ancienne version du produit, etc.)
- Les ressources listées en sont pas exhaustives (liste des CCTP non exhaustive, idem pour les rapports de stage, les revues de presses, etc.)
- Il manque des informations essentielles : lien vers la communauté matrix, lien vers GTR3, etc.

**Une mise à jour de la page s'impose donc. Maintenant la question est de savoir sous quelle forme.**

Sous sa forme actuelle, cela nous impose de régulièrement tenir à jour la page à chaque nouvelle ressource publiée (rapport de stage, cctp, etc.). Cela implique donc une double mise à jour : sur le serveur qui héberge la donnée initiale et sur le site web geotrek.fr

Sous la forme proposée par @numahell plus haut, c'est plus générique et ça évite de devoir mettre à jour à chaque nouvelle ressource. Par contre en effet on perd sûrement des infos puisque tout n'est pas listé.

Je suis d'avis de prendre le meilleur des deux : 
- Avoir une forme épurée comme proposée par @numahell pour pouvoir rapidement rediriger l'utilisateur vers les principales ressources de chaque brique : c'est la majeur partie du temps ce que voudront chercher les utilsateur·ice·s.
- Avoir en dessous une mise en avant plus valorisée de la communauté et des moyens d'entrer en contact avec (matrix, liste de diffusion). 
- Ensuite lister l'ensemble des ressources restantes. Toutefois, plutôt que d'essayer de les lister exhaustivement, plutôt résumer en quelques mots les contenus puis renvoyer directement vers les dossiers. Ainsi plutôt que de lister l'ensemble des CCTP on résume en une phrase le contenu du dossier et on redirige ensuite l'utilisateur vers le dossier. Idem pour stages, outils, groupe de travail, comité de pilotage, présentations, etc. En fait ces sections sont des ressources complémentaires approfondies mais qui ne sont pas forcément des informations recherchées en priorité (le guide de saisie des randonnées du Gard peut être utile pour avoir une inspiration mais ce n'est pas une ressource prioritaire à mettre en avant).
- Exception : les rencontres. On peut continuer de lister des choses dans les rencontres car de toute manière on sait que le contenu ne va pas évoluer trop souvent. Donc je ne voit pas de raison de ne pas lister les ressources des rencontres. Toutefois j'inverserais l'ordre pour faire de l'anti-chronologique car les ressources qu'on risque de chercher en premier sont les dernières et pas forcément celles de 2016. Et ça va à l'encontre de ton avis @camillemonchicourt mais pourquoi ne pas faire une page sur le site dédiée aux rencontres ? Ca expliquerai le concept et listerai dans un endroit dédié les thématiques abordées (aucun endroit sur le site ne présent le concept des rencontres il me semble).

Je trouve que cette proposition de compromis semble plutôt adaptée à l'usage effectif de cette page de ressources tout en essayant d'être complet. 

Cependant vous aurez remarqué que certains éléments ne rentrent pas dans ce que j'ai listé avant : 
- Section "Revue de presse" : là on ne peut pas vraiment rediriger vers un dossier. Mais lister de manière exhaustive les articles implique une mise à jour régulière de la page (d'ailleurs je doute que la revue de presse soit complète).
- Section "Pour aller plus loin" : il s'agit essentiellement d'articles techniques de Makina Corpus. On pourrait juste rediriger vers leur section de blog filtrée par thématique Geotrek ?
- Section "Vidéos" : je trouve que toutes les vidéos présentes dans cette section sont datées et pas très à jour hormis la vidéo de présentation générale du produit mais qui est déjà en avant sur la page d'accueil. Je propose donc de retirer cette section.
- Tutoriels : idem, retirer la section qui n'est plus à jour

Liens vers des démos : aujourd'hui je trouve que les demos de Geotrek ne sont pas vraiment mises en avant sur le site. J'aimerai travailler à des démos plus propres (des données de test complètes) ave cet sans segmentation dynamique. Quand ce sera fait on pourrait imaginer une page dédiée ou une section vraiment bien mise en avant pour que l'utilisateur puisse trouver facilement une démo parce qu'actuellement il faut chercher pour la trouver ...

Pour ce sujet on peut aussi prévoir un temps d'échange oral pour trouver un accord et faire des compromis. Je rappel le constat initial : la page des ressources n'est pas à jour et il faudrait qu'on puisse lui donner un coup de jeune malgré nos divergences d'opinions sur certains aspect graphiques / organisationnels.

**Comment by camillemonchicourt** [comment]
Salut.
Oui, je partage le constat et l’intérêt de la proposition de @numahell avec un allègement de la page, une simplification et une meilleure lisibilité des gros blocs de ressources, sans forcément les détailler.

- OK pour commencer par la documentation, ressource essentielle et première.
- Ensuite des liens vers démos. Pour celles-ci, https://geotrekdemo.ecrins-parcnational.fr (admin / admin), https://gtr3demo.ecrins-parcnational.fr et https://geotrek.ecrins-parcnational.fr/ressources/technique/2022-test-widget.html me vont bien. Ou sinon celles sur xxxx.geotrek.fr. Leur contenu pourraient être mieux mais elles ont le mérite d'exister et sont très utiles aux nouveaux utilisateurs qui s'amusent avec.
- Ensuite les canaux d'information/communication
- Ensuite en effet, les autres ressources, sans les lister, mais juste avec leur catégorie et une explication : 
   - Présentations
   - Cahiers des charges
   - Ressources techniques
   - Exemples de conventions
   - Guides utilisateurs
   - COPIL
   - Groupes de travail
   - Rapports de stage
   - ...
- Pour les rencontres, je ne sais pas si ça mérite une partie dédiée, pourquoi. Même si on fait une actu à chaque nouvelle rencontre. Donc j'ai pas d'avis tranché, sur leur faire une section dans cette page permettant d'accéder essentiellement aux ressources des présentations qui y ont été faites, ou alors leur faire une page dédiée
- Pour la revue de presse, c'est intéressant, mais à mettre à jour. A voir
- Idem pour "En savoir plus", c'est peut-être à aborder autrement, mais juste un lien vers la rubrique "Geotrek" de votre site web ne me semble pas idéal

**Comment by babastienne** [comment]
Depuis plusieurs mois le site web a été mis à jour pour mieux présenter les ressources et séparer sur une page dédiée les éléments relatifs aux rencontres Geotrek.
