### ISSUE TITLE
Ajouter un nouveau filtre "Régions" sur la carte des utilisateurs

### ISSUE THREAD

**Issue by bruhnild** [makinacorpus/Geotrek-website#68]
En ajoutant la nouvelle structure Auvergne-Rhones-Alpes sur la carte des utilisateurs je me suis rendue compte qu'elle recouvrait toutes celles du dessous (CD05, PNR Vercors pour n'en citer que quelques unes) et bloquait les interactions de l'infobulle au survol.

A priori il n'existe pas de moyen de la faire passer en arrière plan par rapport aux autres. Il y a d'autres structures qui se superposent déjà comme le Gard et la Lozère qui passent sur le PN Cévennes mais pour ça il existe les filtres.

Il serait pratique d'avoir un nouveau filtre "Régions" pour gérer les périmètres très étendus comme celui de la région AURA et peut être affiner le filtre "Autres organismes" un peu trop généraliste (comcom, OT, communes, pays)? 

En attendant de trouver une solution pérenne j'ai désactivé la structure AURA de la carte des utilisateurs.

![image](https://github.com/GeotrekCE/Geotrek-website/assets/26433045/cf6e121d-ebb0-40ea-b97a-d228be6a0ce3)

**Comment by juggler31** [comment]
L'issue est faite, et je sais pas si  c'est le mieux d'en parler ici.

Mais ce ne serait pas plus pratique d'avoir l'infobulle qui apparaît au click plutot que au survol ?

**Comment by marcantoinedupre** [comment]
Je pense que c'est mieux au survol. Il faudrait juste la faire disparaître quand le curseur quitte la zone.

**Comment by babastienne** [comment]
Sujet tiers tracé dans [ce ticket](https://github.com/GeotrekCE/Geotrek-website/issues/71)

Je clôture celui-ci.
