### ISSUE TITLE
Modification des liens doc produits

### ISSUE THREAD

**Issue by babastienne** [makinacorpus/Geotrek-website#72]
**Sur la page Produits**

- Pour Geotrek-Rando il faudrait que le lien de la doc redirige vers [https://geotrek-rando-v3.readthedocs.io/](https://geotrek-rando-v3.readthedocs.io/)

- Pour Geotrek-Widget il faudrait que le lien de la doc redirige vers [https://geotrek-rando-widget.readthedocs.io/](https://geotrek-rando-widget.readthedocs.io/)

**Comment by bruhnild** [comment]
https://github.com/GeotrekCE/Geotrek-website/pull/73

**Comment by babastienne** [comment]
Thanks :pray:
